# Dependencies
highlighter:      rouge

plugins: [jekyll-paginate]

# Permalinks
permalink:        pretty

# Setup
title:            derbenoo
tagline:          'IT-Sec stuff'
description:      'PH44N2NVUkRdai 44QVREPyp+Pg=='
url:              'https://derbenoo.github.io'
baseurl:          ''

author:
  name:           'Benjamin Assadsolimani'
  url:            https://twitter.com/derbenoo

paginate:         5

# Custom vars

github:
  repo:           https://github.com/derbenoo
